In [1]:
import pandas as pd
import requests

In [2]:
url = "https://data.cdc.gov/resource/i46a-9kgh.json"
params = {
    "$select": "stateabbr,countyname,countyfips,BINGE_AdjPrev",
    "stateabbr": "CA"
}

r = requests.get(url, params = params)
r.raise_for_status()

binge_ca = pd.DataFrame(r.json())

In [3]:

binge_ca.rename(columns={'countyname': 'County'}, inplace=True)
binge_ca.head()

  stateabbr  County countyfips BINGE_AdjPrev
0        CA  Solano      06095          16.3
1        CA  Placer      06061          18.7
2        CA   Kings      06031          16.9
3        CA  Fresno      06019          14.5
4        CA  Amador      06005          19.9

In [4]:
income_path = "../data/raw/2023-income-limits.csv"

income_df = pd.read_csv(income_path)
income_df.head(5)

,County,AMI,ALI_1,ALI_2,ALI_3,ALI_4,ALI_5,ALI_6,ALI_7,ALI_8,...,LI_7,LI_8,MOD_1,MOD_2,MOD_3,MOD_4,MOD_5,MOD_6,MOD_7,MOD_8
0,Alameda,147900,15550,17750,20000,22200,24000,25750,27550,29300,...,139100,148050,124250,142000,159750,177500,191700,205900,220100,234300
1,Alpine,114600,12050,13750,15500,17200,18600,19950,21350,22700,...,95400,101550,96250,110000,123750,137500,148500,159500,170500,181500
2,Amador,101200,10650,12150,13700,15200,16400,17650,18850,20050,...,91000,96850,85000,97150,109300,121450,131150,140900,150600,160300
3,Butte,91600,9650,11000,12400,13750,14850,15950,17050,18150,...,81800,87100,76950,87900,98900,109900,118700,127500,136300,145050
4,Calaveras,96200,10100,11550,13000,14450,15600,16750,17900,19050,...,94550,100650,80800,92350,103900,115450,124700,133900,143150,152400

In [5]:
df = pd.merge(income_df, binge_ca, on='County')
df = df.loc[:, ['County', 'stateabbr', 'countyfips', 'BINGE_AdjPrev', 'AMI']]
df.head()

      County stateabbr countyfips BINGE_AdjPrev     AMI
0    Alameda        CA      06001          16.3  147900
1     Alpine        CA      06003          20.0  114600
2     Amador        CA      06005          19.9  101200
3      Butte        CA      06007          18.8   91600
4  Calaveras        CA      06009          19.3   96200

In [6]:
print(df.shape)

(58, 5)

In [9]:
output_file = '../data/interim/combined_data.csv'
df.to_csv(
    output_file,
    index=False,
    encoding="utf-8"
)

print(f"Output file: {output_file}")

Output file: ../data/interim/combined_data.csv