# CLEANING
1. Missing values
  - Analyze if they could actually be valid
  - Remove the -1s
2. Check invalid pairs
  - non-existent person
  - same person connection
3. Use plots, statistical summaries to identify outliers

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
print('setup complete')

setup complete

In [19]:
calls_data = pd.read_csv('../data/raw/calls.csv')
calls_data.head()

   timestamp  caller  callee  duration
0        184     300     301       121
1       3920     512     299       670
2       5623     301     300       504
3       9252     401     457        -1
4      15466     512       0         5

In [20]:
#Empty scans are marked with user B = -1 and RSSI = 0, so we should remove these
print(calls_data.shape)
calls_data = calls_data[calls_data['duration'] != -1]
print(calls_data.shape)

(3600, 4)
(3234, 4)

In [21]:
calls_data.isna().sum()

timestamp    0
caller       0
callee       0
duration     0
dtype: int64

In [ ]:
fb_friends = pd.read_csv('../data/raw/fb_friends.csv')



fb_friends = fb_friends.rename(columns={fb_friends.columns[0]: 'user_a'})
fb_friends.head()

   user_a  user_b
0       0     512
1       0     263
2       0     525
3       0     285
4       0     543

In [28]:
sms = pd.read_csv('../data/raw/sms.csv')

sms.head()

   timestamp  sender  recipient
0         18     370        512
1         37     512        370
2        126     370        512
3        134       0        512
4        312     137        136

In [29]:
#ids are 0-847 (inclusive)

ids_set = set(range(847+1))
display(fb_friends[~fb_friends['user_a'].isin(ids_set)])
display(fb_friends[fb_friends['user_a'] == fb_friends['user_b']]) # something invalid, can't be friends with yourself  

display(sms[sms['sender'] == sms['recipient']])
display(sms[sms['sender'] == sms['recipient']])

Empty DataFrame
Columns: [user_a, user_b]
Index: []

      user_a  user_b
536      269     269
622      527     527
2209      71      71
2648     341     341
3846     644     644
4405     666     666
5128     187     187
5369     199     199
5507     207     207
5829     476     476
6004     739     739

Empty DataFrame
Columns: [timestamp, sender, recipient]
Index: []

Empty DataFrame
Columns: [timestamp, sender, recipient]
Index: []

In [30]:
print(fb_friends.shape)
fb_friends = fb_friends[~(fb_friends['user_a'] == fb_friends['user_b'])]
print(fb_friends.shape)

(6429, 2)
(6418, 2)