In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
print('setup complete')

setup complete

In [2]:
calls_data = pd.read_csv('../data/raw/calls.csv')
bt_data = pd.read_csv('../data/raw/bt_symmetric.csv')
fb_data = pd.read_csv('../data/raw/fb_friends.csv')
sms_data = pd.read_csv('../data/raw/sms.csv')

In [3]:
display(calls_data.describe())
display(bt_data.describe())
display(fb_data.describe())
display(sms_data.describe())

          timestamp       caller       callee     duration
count  3.600000e+03  3600.000000  3600.000000  3600.000000
mean   1.281670e+06   349.840833   354.581111    56.790833
std    6.662889e+05   226.328594   221.136143   176.862896
min    1.840000e+02     0.000000     0.000000    -1.000000
25%    7.501832e+05   143.000000   163.750000     0.000000
50%    1.250542e+06   335.000000   354.000000    10.000000
75%    1.819620e+06   560.000000   552.000000    50.000000
max    2.416399e+06   846.000000   845.000000  5138.000000

        # timestamp        user_a        user_b          rssi
count  5.474289e+06  5.474289e+06  5.474289e+06  5.474289e+06
mean   1.217629e+06  3.791028e+02  9.568739e+01 -4.994969e+01
std    6.786570e+05  1.947784e+02  1.495550e+02  4.207211e+01
min    0.000000e+00  0.000000e+00 -2.000000e+00 -1.070000e+02
25%    6.762000e+05  2.210000e+02 -1.000000e+00 -8.800000e+01
50%    1.206000e+06  3.940000e+02 -1.000000e+00 -7.400000e+01
75%    1.801500e+06  5.430000e+02  1.660000e+02  0.000000e+00
max    2.418900e+06  8.450000e+02  7.040000e+02  2.000000e+01

          # user_a       user_b
count  6429.000000  6429.000000
mean    258.457925   542.396640
std     183.898553   204.571573
min       0.000000    13.000000
25%     104.000000   393.000000
50%     221.000000   564.000000
75%     386.000000   711.000000
max     824.000000   850.000000

          timestamp        sender     recipient
count  2.433300e+04  24333.000000  24333.000000
mean   1.161996e+06    335.711421    334.693996
std    6.883014e+05    212.399709    213.045789
min    1.800000e+01      0.000000      0.000000
25%    5.744050e+05    152.000000    149.000000
50%    1.080494e+06    296.000000    296.000000
75%    1.729376e+06    531.000000    540.000000
max    2.418982e+06    846.000000    846.000000