In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [4]:
csv_path = '../data/raw/music_survey_raw.csv'
df = pd.read_csv(csv_path)
df

,Timestamp,Email Address,What gender are you?,How much do you like rap (music genre) on scale of 1 to 10?,How much do you like pop (music genre) on a scale of 1 to 10?
0,7/7/2026 10:43:01,william.kaden.liu@gmail.com,Male,8,7
1,7/7/2026 10:43:16,ema.kaludjerovic23@gmail.com,Female,7,8
2,7/7/2026 10:43:18,shelyndeli@gmail.com,Female,7,8
3,7/7/2026 10:43:56,brianqian09@gmail.com,Male,7,8
4,7/7/2026 10:44:01,lswagner70@gmail.com,Male,6,8
5,7/7/2026 10:44:02,sahilqureshi2008@gmail.com,Male,6,7
6,7/7/2026 10:44:13,yuchenwang761@gmail.com,Male,10,3
7,7/7/2026 10:44:27,warrensuca@gmail.com,Male,8,4
8,7/7/2026 10:44:32,samarthgaggar2010@gmail.com,Male,8,5
9,7/7/2026 10:44:43,sportsperson3015@gmail.com,Male,7,6
10,7/7/2026 10:45:25,ridhima.v.kapoor@gmail.com,Female,3,8
11,7/7/2026 10:45:33,mrlijerry@gmail.com,Male,2,5
12,7/7/2026 10:46:32,elaprolupranav@gmail.com,Male,6,7
13,7/7/2026 10:47:06,advaitghosh22@gmail.com,Male,9,9
14,7/7/2026 10:47:09,shreyasb609@gmail.com,Male,2,5
15,7/7/2026 10:47:10,soniarshin@gmail.com,Female,5,8
16,7/7/2026 10:47:15,hu.ashley10@gmail.com,Female,9,9
17,7/7/2026 10:47:51,advay422@gmail.com,Male,8,7
18,7/7/2026 10:48:40,bpark4467@gmail.com,Male,7,8
19,7/7/2026 10:50:46,michaelzytang@gmail.com,Male,8,7

In [ ]:
df.isna().head()

,Timestamp,Email Address,What gender are you?,How much do you like rap (music genre) on scale of 1 to 10?,How much do you like pop (music genre) on a scale of 1 to 10?
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
5,False,False,False,False,False
6,False,False,False,False,False
7,False,False,False,False,False
8,False,False,False,False,False
9,False,False,False,False,False
10,False,False,False,False,False
11,False,False,False,False,False
12,False,False,False,False,False
13,False,False,False,False,False
14,False,False,False,False,False
15,False,False,False,False,False
16,False,False,False,False,False
17,False,False,False,False,False
18,False,False,False,False,False
19,False,False,False,False,False

In [6]:
df.isna().sum().head()

Timestamp                                                        0
Email Address                                                    0
What gender are you?                                             0
How much do you like rap (music genre) on scale of 1 to 10?      0
How much do you like pop (music genre) on a scale of 1 to 10?    0
dtype: int64

## There are no null values

In [ ]:
types = df.dtypes
display(types)

Timestamp                                                          str
Email Address                                                      str
What gender are you?                                               str
How much do you like rap (music genre) on scale of 1 to 10?      int64
How much do you like pop (music genre) on a scale of 1 to 10?    int64
dtype: object